### ISSUE TITLE
enhancement: and/or/not syntax

### ISSUE THREAD

**Issue by kabo1234** [macrojd/tag-summary#1]
hi there,

this is so awesome and easy! I just have one suggestion with regards to limiting/expanding results.

Block1: blabla
#ABC

Block 2: blabababall
#DEF

Block 3: tada
#ABC #DEF

I think it would be great if the syntax could be 

tags: #ABC #DEF
-> will only show blocks that have BOTH tags - Block 3 in the sample

tags: #ABC or #DEF 
-> shows all three blocks

tags: #ABC not #DEF
-> only Block 1

Hope this makes sense - I think this would make it so versatile.

**Comment by macrojd** [comment]
Yes. I realized that I needed this feature when I was writing the instructions. The only issue is that the and/or/not syntax is complicated for non-programmers and it is complex to process when more than two tags are included. What I’m thinking is to provide two more labels. The tags: label will work the same way (OR). The include: label will specify the tags that the paragraph must include (AND), and the exclude: label will specify the tags that the paragraph must not include (NOT). The tags for each label are specified separated by a space, which makes it easy for the user, and I can process the labels one by one, which makes it easy for me to program. If the plug-in is approved, I can add this feature next week.

**Comment by kabo1234** [comment]
Hi again,
thanks for the quick reply - that sounds like a very workable solution! 
I did have a little giggle, as I've been around library catalogues for so long that and/or/not is the simplest syntax that I know in comparison to any of the queries and searches that are currently available in Obsidian and it's plugins ;) 
But I sincerely appreciate your concern for non-programmers as I am one of them!
