### ISSUE TITLE
Add support for non-English letters in tags

### ISSUE THREAD

**Issue by mnaoumov** [macrojd/tag-summary#10]
Currently

````
```add-summary
tags: #tag
```
````

works properly

But similar query with Cyrillic letters

````
```add-summary
tags: #тег
```
````

outputs `There are no blocks that match the specified tags.`

**Comment by macrojd** [comment]
Hi, Michael. Thanks for the help. I'm busy this week, but I'll test the changes you suggested and post the updates in a few days.

JD
www.jdgauchat.com
