### ISSUE TITLE
Lines of text of different length being treated as separate blocks 

### ISSUE THREAD

**Issue by daxmonson** [macrojd/tag-summary#13]
If a line isn't as long as the previous line it gets treated as separate block on the summary page, wondering if that's by design or a bug? 

This part of the readme seems like it should all be rendered as one block in the summary page as long as there isn't a completely empty line between text: "The plugin considers a block of text to be all the text between empty lines. If you add an empty line in the middle of a paragraph or a block of text, the plugin will consider that as two different blocks."

Have some (many) huge blocks which have lines that aren't uniform length that would be nice to be render whole and not in pieces. I know I could hard wrap everything outside of Obsidian in a word processor or code editor, but these are things I have to read as I go in Obsidian so a code editor would be clunky. 

Thanks for taking a look here and for the recent update, it's great work 👍

**Comment by macrojd** [comment]
Hi. It could be a bug. If you can send me a copy of an md file with a text that shows this behavior, it would be great. You don't need to send me your notes, just take a note that is not working and replace your writing with random text. My email is info@jdgauchat.com

**Comment by daxmonson** [comment]
Cool, done. Thank you.
