### ISSUE TITLE
List Items doesn't work

### ISSUE THREAD

**Issue by rawxrawxrawx** [macrojd/tag-summary#16]
Even with List Items activated in the prefs, Tag Summary still outputs the whole list, including bullet points not containing the tag.

**Comment by macrojd** [comment]
Hi. Thanks for letting me know. There is a new version available that fixes the bug. (2.1.5). It usually takes 24 hours to become available. When you get it, let me know if it works for you.

**Comment by rawxrawxrawx** [comment]
Thanks, but, well, I just updated and now it doesn't work at all.

**Comment by rawxrawxrawx** [comment]
Scratch that, it's working just fine now. Thanks, great plugin!
