### ISSUE TITLE
【bug report】 the plugin doesn't show the tagged paragraph

### ISSUE THREAD

**Issue by Ravenclawer** [macrojd/tag-summary#4]
I have a test note for this plugin but the code doesn't capture the tagged paragraphs 
![image](https://user-images.githubusercontent.com/73892411/200161048-8cbcda80-ec49-4d8e-b8cf-b4035ce40c51.png)
![image](https://user-images.githubusercontent.com/73892411/200161062-6aa915a0-7a9d-4011-922d-623b0e466815.png)
I'm currently using windows 10 and obsidian 1.0.3

**Comment by macrojd** [comment]
Hi. Try creating the summary in a different note. At first, I wasn't sure how the system worked, so to avoid recursive reading the plug-in doesn't look for matches in the current file. I may change that later if I can confirm that there won't be any issues.

**Comment by Ravenclawer** [comment]
Thank you very much， I created the summary in another note and it works like a charm.
I think this plugin fills a big feature gap in the obsidian feature that the tag can only be used to navigate to page-level content, making the tag far less appealing than wikilink to a note with the same name. but now with this plugin, we can congregate content at the paragraph level to a new page with tags. this is really a game changer for tag in obsidian and for users who likes using tags in their writing.
