### ISSUE TITLE
[Feature Request] Restrict the search scope

### ISSUE THREAD

**Issue by Seraphli** [macrojd/tag-summary#5]
Great plugin! I have been searching for such a plugin to do a summary. I have a request for several features.
1. Can I restrict the search scope to the current file? Or some files, even some folders?
2. Can the search pattern be customized? Instead of searching for tags, the plugin can search for words with regex.

The first feature is the one I want most. I'm using [obsidian-annotator](https://github.com/elias-sundqvist/obsidian-annotator) to read papers. I was trying to find a way to summarize the annotations and display only the important part of them. The plugin currently can not only search in the current file. So I cannot use it. With this feature, the plugin will help a lot. So compare to this, other features are not that important at this moment.

**Comment by macrojd** [comment]
Hi. Yes, my intention is to make the plugin scan the note where the summary was created and allow the user to select which folders and files to scan. I just need to take the time to do it. Maybe I get it done by next week. Word searching is another matter entirely. At first, the plugin was scanning all files and for that reason it was rejected. I was asked to check if the file contains a tag before scanning it. Searching for words requires the plugin to scan every file and it could get rejected again. So it is not possible. At least not for me.

**Comment by Seraphli** [comment]
Good to hear that you have the plan to search in the current file. About word searching, I'm not saying to search all files. It will cause performance issues. And I think users usually want a summary of some files. Checking the tags of files is a good idea.

**Comment by macrojd** [comment]
Hi. The version 1.2.0 now search for tags in the summary's file. I will add the option to search in specific folders and files later when I have the time. Thanks for the advice.
