### ISSUE TITLE
hope it supports more languages.

### ISSUE THREAD

**Issue by zhaoscsc** [macrojd/tag-summary#7]
I tried Chinese. Unfortunately, it doesn't support

**Comment by macrojd** [comment]
Yes. I mentioned that in the README (in the section Known Issues). You can only create summaries with tags that include Latin letters a to z, A to Z, and the numbers 0 to 9. Unfortunately, it takes time to modify the plugin and test it for multiple languages, and right now I'm working on other projects. Maybe I'm able to do it next year.

**Comment by macrojd** [comment]
There is a new version available 2.0.0 that supports every language. Please, let me know if it works for you. Thanks!
